package actions

/**
* Generate infrastructure module
*
* This module will generate a new infrastructure module
*
*
* @param name name of the module
* @param url url of the module
* @param type type of the module
*
* The generated code MUST implement the Repository interface
* - Setup() error
* - Shutdown() error
 */

const INFRASTRUCTURE_TPL = `// Code generated by main.go; DO NOT EDIT.

package {{.URL}}

type {{.NameCapitalized}} struct {}

func New{{.NameCapitalized}}() (*{{.NameCapitalized}}, error) {
  panic("implement me")
}

func (m *{{.NameCapitalized}}) Setup() error {
  panic("implement me")
}

func (m *{{.NameCapitalized}}) Shutdown() error {
  panic("implement me")
}
`

